config/routes.rb
Rails.application.routes.draw do
  resources :mice
  resources :domains
  resources :regions
  resources :continents
  
  root 'continents#index'
  
  get '/continents/create/id' => 'continents#create'
  

end

app/controllers/mice_controller.rb
class MiceController < ApplicationController
  before_action :set_mouse, only: [:show, :edit, :update, :destroy]

  # GET /mice
  # GET /mice.json
  def index
    @mice = Mouse.all
  end

  # GET /mice/1
  # GET /mice/1.json
  def show
  end

  # GET /mice/new
  def new
    @mouse = Mouse.new
  end

  # GET /mice/1/edit
  def edit
  end

  # POST /mice
  # POST /mice.json
  def create
    @mouse = Mouse.new(mouse_params)

    respond_to do |format|
      if @mouse.save
        format.html { redirect_to @mouse, notice: 'Mouse was successfully created.' }
        format.json { render :show, status: :created, location: @mouse }
      else
        format.html { render :new }
        format.json { render json: @mouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mice/1
  # PATCH/PUT /mice/1.json
  def update
    respond_to do |format|
      if @mouse.update(mouse_params)
        format.html { redirect_to @mouse, notice: 'Mouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @mouse }
      else
        format.html { render :edit }
        format.json { render json: @mouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mice/1
  # DELETE /mice/1.json
  def destroy
    @mouse.destroy
    respond_to do |format|
      format.html { redirect_to mice_url, notice: 'Mouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mouse
      @mouse = Mouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mouse_params
      params.require(:mouse).permit(:name, :domain_id)
    end
end

app/helpers/mice_helper.rb
module MiceHelper
end

app/views/mice/_form.html.erb
<%= form_for(@mouse) do |f| %>
  <% if @mouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mouse.errors.count, "error") %> prohibited this mouse from being saved:</h2>

      <ul>
      <% @mouse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :domain_id %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mice/edit.html.erb
<h1>Editing Mouse</h1>

<%= render 'form' %>

<%= link_to 'Show', @mouse %> |
<%= link_to 'Back', mice_path %>

app/views/mice/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mice</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mice.each do |mouse| %>
      <tr>
        <td><%= mouse.name %></td>
        <td><%= mouse.domain %></td>
        <td><%= link_to 'Show', mouse %></td>
        <td><%= link_to 'Edit', edit_mouse_path(mouse) %></td>
        <td><%= link_to 'Destroy', mouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mouse', new_mouse_path %>

app/views/mice/new.html.erb
<h1>New Mouse</h1>

<%= render 'form' %>

<%= link_to 'Back', mice_path %>

app/views/mice/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mouse.name %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @mouse.domain %>
</p>

<%= link_to 'Edit', edit_mouse_path(@mouse) %> |
<%= link_to 'Back', mice_path %>