config/routes.rb
Rails.application.routes.draw do
  resources :mice
  resources :domains
  resources :regions
  resources :continents
  
  root 'continents#index'
  
  get '/continents/create/id' => 'continents#create'
  

end

app/models/continent.rb
class Continent < ActiveRecord::Base
    has_many :regions
    has_many :domains, through: :regions
    
    accepts_nested_attributes_for   :regions, reject_if: :all_blank
    accepts_nested_attributes_for   :domains
                                    
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  before_action :set_continent, only: [:show, :edit, :update, :destroy]

  # GET /continents
  # GET /continents.json
  def index
    @continents = Continent.all
    
    ### Unelegant - this writes over Regionw we already have access too via the model
    #@regions = []
      # need all regions to list in nested form
    #@continents.each do | x | x = x.regions end
  end

  # GET /continents/1
  # GET /continents/1.json
  def show
  end

  # GET /continents/new
  def new
    @continent = Continent.new
  end

  # GET /continents/1/edit
  def edit
  end

  # POST /continents
  # POST /continents.json
  def create
    @continent = Continent.new(continent_params)

    respond_to do |format|
      if @continent.save
        format.html { redirect_to @continent, notice: 'Continent was successfully created.' }
        format.json { render :show, status: :created, location: @continent }
      else
        format.html { render :new }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /continents/1
  # PATCH/PUT /continents/1.json
  def update
    respond_to do |format|
      if @continent.update(continent_params)
        format.html { redirect_to @continent, notice: 'Continent was successfully updated.' }
        format.json { render :show, status: :ok, location: @continent }
      else
        format.html { render :edit }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /continents/1
  # DELETE /continents/1.json
  def destroy
    @continent.destroy
    respond_to do |format|
      format.html { redirect_to continents_url, notice: 'Continent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_continent
      @continent = Continent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def continent_params
      params.require(:continent).permit(:name, :id, 
        { region_attributes: [:id, :_destroy, :name, :continent_id]})
    end
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/views/continents/_form.html.erb
<%= form_for(@continent) do |f| %>
  <% if @continent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@continent.errors.count, "error") %> prohibited this continent from being saved:</h2>

      <ul>
      <% @continent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/continents/edit.html.erb
<h1>Editing Continent</h1>

<%= render 'form' %>

<%= link_to 'Show', @continent %> |
<%= link_to 'Back', continents_path %>

app/views/continents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Continents - <%= pluralize(@continents.count, "continents") %> total ...</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @continents.each do |x| %>
      <tr>
        <td><%= x.name %></td>
        <td> <%= pluralize(x.regions.count, "region") %> </td>
        <td><%= link_to 'Show', x %></td>
        <td><%= link_to 'Edit', edit_continent_path(x) %></td>
        <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% x.regions.each do | theregions | %>
        <%= render partial: 'shared/showregion', locals: {r: theregions} %>
      <% end %>    
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Continent', new_continent_path %>

app/views/continents/new.html.erb
<h1>New Continent</h1>

<%= render 'form' %>

<%= link_to 'Back', continents_path %>

app/views/continents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @continent.name %>
</p>

<%= link_to 'Edit', edit_continent_path(@continent) %> |
<%= link_to 'Back', continents_path %>